Concordia-Campus-Guide/Concordia-Campus-Guide

app/build.gradle
app/src/debug/res/values/google_maps_api.xml
app/src/main/AndroidManifest.xml
app/src/main/java/com/example/concordia_campus_guide/MapsActivity.java
app/src/main/res/layout/activity_maps.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml
app/src/release/res/values/google_maps_api.xml

currently, the app shows a map with the location hardcoded.

integrated Material Component and Google Map API with the project

---

.gitignore
app/src/main/AndroidManifest.xml

*PLEASE READ CAREFULLY*
you will need to add a new file named: "keys.xml". In the following path: Concordia-Campus-Guide/app/src/main/res/values
with the content that I sent on Slack.
I added the file name to the .gitignore so that it would not be tracked anymore

adding keys to git ignore

---

.github/ISSUE_TEMPLATE/bug_report

I created a bug template that will be used whenever we open a new bug to stay consistent with our report structure

Created a bug report template

---

.github/ISSUE_TEMPLATE/bug_report.md

I updated the template of the bug report and made it possible to use when creating an issue.

Updating Bug report template

---

app/src/androidTest/java/com/example/concordia_campus_guide/InfoCardFragmentIntegrationTest.java
app/src/androidTest/java/com/example/concordia_campus_guide/InstrumentalTests/LocationFragmentInstrumentalTest.java
app/src/androidTest/java/com/example/concordia_campus_guide/LocationFragmentUITest.java
app/src/main/java/com/example/concordia_campus_guide/Activities/MainActivity.java
app/src/main/java/com/example/concordia_campus_guide/Fragments/InfoCardFragment/InfoCardFragment.java
app/src/main/java/com/example/concordia_campus_guide/Fragments/InfoCardFragment/InfoCardFragmentViewModel.java
app/src/main/java/com/example/concordia_campus_guide/Fragments/LocationFragment/LocationFragment.java
app/src/main/java/com/example/concordia_campus_guide/Fragments/LocationFragment/LocationFragmentViewModel.java
app/src/main/res/layout/activity_main.xml
app/src/test/java/com/example/concordia_campus_guide/LocationFragmentViewModelTest.java

Added unit tests for LocationFragmentViewModel.
Created a fragments folder where our fragments will go

Test/#22: added unit tests for LocationFragmentViewModel

---

.idea/misc.xml
app/src/main/AndroidManifest.xml
app/src/main/java/com/example/concordia_campus_guide/Activities/MainActivity.java
app/src/main/java/com/example/concordia_campus_guide/Activities/RoutesActivity.java
app/src/main/java/com/example/concordia_campus_guide/Activities/SearchActivity.java
app/src/main/res/drawable/ic_arrow_back_24dp.xml
app/src/main/res/drawable/ic_my_location_24dp.xml
app/src/main/res/drawable/ic_place_24dp.xml
app/src/main/res/drawable/ic_search_24dp.xml
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/content_routes.xml
app/src/main/res/layout/menu_routes.xml
app/src/main/res/layout/routes_activity.xml
app/src/main/res/layout/search_activity.xml
app/src/main/res/menu/menu.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml

Work in progress, added toolbar, search button and search page

#38/select indoor location 3

---

app/src/main/java/com/example/concordia_campus_guide/Adapters/FloorPickerAdapter.java
app/src/main/java/com/example/concordia_campus_guide/Fragments/LocationFragment/LocationFragment.java

As per the PO's request, the floor picker is selected at the top-most floor level by default.

#88: floor picker indicates top-most floor by default

---

.idea/misc.xml
app/src/main/java/com/example/concordia_campus_guide/Fragments/LocationFragment/LocationFragment.java
app/src/main/java/com/example/concordia_campus_guide/Fragments/LocationFragment/LocationFragmentViewModel.java

I modified the application to display the user's location when launching the application according to the PO's request. In case the user doesn't want to enable their current location, the map's view will be redirected towards the SGW campus.

#90: Displaying the user location when lauching the application

---

app/build.gradle
app/src/main/java/com/example/concordia_campus_guide/Models/Profile.java
app/src/main/java/com/example/concordia_campus_guide/Models/Route.java
app/src/main/java/com/example/concordia_campus_guide/Models/TransitType.java
app/src/test/java/com/example/concordia_campus_guide/ModelTests/DirectionTest.java
app/src/test/java/com/example/concordia_campus_guide/ModelTests/FloorTest.java
app/src/test/java/com/example/concordia_campus_guide/ModelTests/ListOfCoordinatesTest.java
app/src/test/java/com/example/concordia_campus_guide/ModelTests/MyCurrentPlaceTest.java
app/src/test/java/com/example/concordia_campus_guide/ModelTests/ProfileTest.java
app/src/test/java/com/example/concordia_campus_guide/ModelTests/RoomModelTest.java
app/src/test/java/com/example/concordia_campus_guide/ModelTests/RoomsTest.java
app/src/test/java/com/example/concordia_campus_guide/ModelTests/RouteTest.java
app/src/test/java/com/example/concordia_campus_guide/ModelTests/WalkingPointTest.java
app/src/test/java/com/example/concordia_campus_guide/ModelTests/WalkingPointsTest.java
build.gradle

* Fixed SonarQube and Jacoco issue
* Excluded classes that should not be affecting the test code coverage
* Added 8 unit test classes for our models to reach 30% code coverage in the project
* updated some models to support testability

#115: added unit tests and fixed jacoco and sonarqube issue

---

.idea/misc.xml
app/src/main/java/com/example/concordia_campus_guide/Activities/MainActivity.java
app/src/main/java/com/example/concordia_campus_guide/Activities/RoutesActivity.java
app/src/main/java/com/example/concordia_campus_guide/Activities/RoutesActivityViewModel.java
app/src/main/java/com/example/concordia_campus_guide/Activities/SearchActivity.java
app/src/main/java/com/example/concordia_campus_guide/Activities/SearchActivityViewModel.java
app/src/main/java/com/example/concordia_campus_guide/Database/Daos/RoomDao.java
app/src/main/java/com/example/concordia_campus_guide/Fragments/InfoCardFragment/InfoCardFragment.java
app/src/main/java/com/example/concordia_campus_guide/Fragments/InfoCardFragment/InfoCardFragmentViewModel.java
app/src/main/java/com/example/concordia_campus_guide/Helper/ViewModelFactory.java
app/src/main/java/com/example/concordia_campus_guide/Models/Building.java
app/src/test/java/com/example/concordia_campus_guide/ViewModel/CalendarViewModelTest.java
app/src/test/java/com/example/concordia_campus_guide/ViewModel/InfoCardFragmentViewModelTest.java
app/src/test/java/com/example/concordia_campus_guide/ViewModel/RoutesActivityViewModelTest.java
app/src/test/java/com/example/concordia_campus_guide/ViewModel/SearchActivityViewModelTest.java

* Added unit tests for InfoCardViewModel, SearchActivityViewModel and RoutesActivityViewModel
* Added a way to decouple the ViewModels from the Context by using a ViewModelBuilder which builds ViewModels with the database, so that it is mockable

#38 select location tests

---

.github/ISSUE_TEMPLATE/improvement-template-.md

I added a template for possible improvement issues that we would like to have in the future if we get the chance. Furthermore, I added the environment section in the bug report template.

#136/Update issue templates

---

app/src/main/res/raw/buildings_info.json

The bug #141 has been fixed by adding the missing center-coordinates to several buildings from SGW campus.

#141/center coordinates bug fix

---

app/src/main/java/com/example/concordia_campus_guide/Fragments/LocationFragment/LocationFragment.java
app/src/main/java/com/example/concordia_campus_guide/Models/RoomModel.java
app/src/main/res/raw/rooms_info.json

fixed some nonunique room codes and added a unique identifier to the room's model

#130: unique room numbers

---

app/src/main/res/raw/walking_points.json

Updated the walking points to include more options.

#40/walking points

---

app/src/main/java/com/example/concordia_campus_guide/Activities/SearchActivity.java
app/src/main/java/com/example/concordia_campus_guide/Models/Helpers/CalendarViewModel.java
app/src/main/res/layout/search_activity.xml

Changed visibility of searchResults and added an onClickListener to update the visibility
Page is displayed when user taps on search icon from main page: 
Search results list appear after the user taps on the search bar:

#144: Search Activity UI Bug Fix

---

app/src/main/java/com/example/concordia_campus_guide/Activities/SearchActivityViewModel.java
app/src/main/java/com/example/concordia_campus_guide/Database/Daos/RoomDao.java

And updated parsing of event location. User will now be required to enter the location of their classroom with this format: Floor_code, room_code (ex. H-9, 963)

#151 Refactor to correctly select room from database 

---

app/src/main/java/com/example/concordia_campus_guide/Fragments/LocationFragment/LocationFragment.java

I removed the zoom buttons since they haven't been used by the user.

#154: removed the zoom buttons

---

app/src/main/java/com/example/concordia_campus_guide/Activities/RoutesActivity.java

Fixed by adding null check since it wasn't being done before which was causing most of our bugs

#155: Fix bug by adding null check

---

app/src/main/java/com/example/concordia_campus_guide/Fragments/LocationFragment/LocationFragmentViewModel.java

I fixed the bug that was mentioned by sonarqube regarding closing the inputStream

#119: fixed the bug of closing the inputStream

---

app/src/main/java/com/example/concordia_campus_guide/Activities/MainActivity.java
app/src/main/res/layout/activity_main.xml

Added proper behavior to info card and explore POI card using 2 different scroll views with their respective fragments and behaviors

#161: Fix bottom sheets to have expected behavior

---

app/src/main/java/com/example/concordia_campus_guide/Activities/MainActivity.java
app/src/main/res/layout/info_card_fragment.xml
app/src/main/res/layout/point_of_interest_fragment.xml

Fixed the height issue that arose from my last PR.
Please note that the back button currently serves to get the explore card. You won't be able to close the app with the back button. **I was unable to find a solution on how to display the explore card after showing the info card...**

#161/bug fix info card height

---

app/src/main/java/com/example/concordia_campus_guide/Activities/RoutesActivity.java
app/src/main/java/com/example/concordia_campus_guide/Activities/RoutesActivityViewModel.java
app/src/main/res/layout/list_routes.xml
app/src/main/res/layout/routes_activity.xml

#94: fixed small UI issue

---

app/src/main/res/layout/point_of_interest_fragment.xml

this should fix the overlap issue

#11: added white background to avoid overlap

---

app/src/main/java/com/example/concordia_campus_guide/Models/Routes/Route.java
app/src/test/java/com/example/concordia_campus_guide/ModelTests/BusTest.java
app/src/test/java/com/example/concordia_campus_guide/ModelTests/CarTest.java
app/src/test/java/com/example/concordia_campus_guide/ModelTests/DirectionTest.java
app/src/test/java/com/example/concordia_campus_guide/ModelTests/RouteTest.java
app/src/test/java/com/example/concordia_campus_guide/ModelTests/SubwayTest.java
app/src/test/java/com/example/concordia_campus_guide/ModelTests/TestUtils/TestUtilsRoutes.java
app/src/test/java/com/example/concordia_campus_guide/ModelTests/TrainTest.java
app/src/test/java/com/example/concordia_campus_guide/ModelTests/WalkTest.java
app/src/test/java/com/example/concordia_campus_guide/ViewModel/RoutesActivityViewModelTest.java

#94: added unit tests for Route class

---

app/src/main/java/com/example/concordia_campus_guide/Fragments/LocationFragment/LocationFragmentViewModel.java

As requested by our team lead. I Hope it helps!

#fix: added marker tags to be able to UI test.

---

app/src/main/java/com/example/concordia_campus_guide/Database/Daos/WalkingPointDao.java
app/src/main/java/com/example/concordia_campus_guide/Fragments/LocationFragment/LocationFragmentViewModel.java
app/src/main/java/com/example/concordia_campus_guide/Helper/PathFinder.java
app/src/main/res/raw/rooms_info.json
app/src/main/res/raw/walking_points.json
app/src/test/java/com/example/concordia_campus_guide/HelpersTest/PathFinderTest.java

Bugs fixed:
- MB building having 2 entrances (1 tunnel and 1 accessible from the street) was not good design. Only the ground floor entrance is kept; the tunnel entrance is changed to a walking point of type NONE
Fixed the bug where multiple rooms with the same placeCode existed. Rooms do not have only the placeCode as uniqueID, therefore we need to fetch the corresponding WalkingPoint depending on the floorCode and placeCode/roomCode.

#11/bug fixes

---

app/build.gradle
app/src/main/java/com/example/concordia_campus_guide/Activities/MainActivity.java
app/src/main/java/com/example/concordia_campus_guide/Activities/PathsActivity.java
app/src/main/java/com/example/concordia_campus_guide/Activities/RoutesActivity.java
app/src/main/java/com/example/concordia_campus_guide/Adapters/RoutesAdapter.java
app/src/main/java/com/example/concordia_campus_guide/Fragments/PathInfoCardFragment/PathInfoCardFragment.java
app/src/main/java/com/example/concordia_campus_guide/Models/Building.java
app/src/test/java/com/example/concordia_campus_guide/Activities/PathsViewModelTest.java
build.gradle
google-maps-services-java-0.10.0/src/test/java/com/google/maps/DirectionsApiTest.java
google-maps-services-java-0.10.0/src/test/java/com/google/maps/PlacesApiTest.java
settings.gradle

removed about 30 code smells just to decrease the number a bit

#118: fixed a few sonarqube code smell issues

---

app/src/main/java/com/example/concordia_campus_guide/Activities/RoutesActivity.java
app/src/main/java/com/example/concordia_campus_guide/Activities/RoutesActivityViewModel.java
app/src/main/java/com/example/concordia_campus_guide/Adapters/RoutesAdapter.java
app/src/test/java/com/example/concordia_campus_guide/ViewModel/RoutesActivityViewModelTest.java

separated some shuttle methods in the routeActivityViewModel to be able to add test cases and added unit tests accordingly

#95 Shuttle Unit test

---

app/build.gradle
app/src/androidTest/java/com/example/concordia_campus_guide/InstrumentalTests/LocationFragmentInstrumentalTest.java
app/src/main/java/com/example/concordia_campus_guide/Fragments/LocationFragment/LocationFragmentViewModel.java
app/src/main/java/com/example/concordia_campus_guide/Global/NotificationStatus.java
app/src/main/java/com/example/concordia_campus_guide/Global/User.java
app/src/test/java/com/example/concordia_campus_guide/Activities/PathsViewModelTest.java
app/src/test/java/com/example/concordia_campus_guide/HelpersTest/NotificationTest.java
app/src/test/java/com/example/concordia_campus_guide/SelectingToFromStateTest.java
app/src/test/java/com/example/concordia_campus_guide/ViewModel/MainActivityViewModelTest.java

I have implemented some unit and instrumental tests. Our test coverage is 76% now

#97: Added several new tests and fixed some

---

app/src/test/java/com/example/concordia_campus_guide/HelpersTest/IndoorPathHeuristicTest.java
app/src/test/java/com/example/concordia_campus_guide/HelpersTest/PathFinderTest.java

I cleaned the testing classes of the PathFinder and Heuristic Classes.

Refactored some testing classes

---

app/src/main/java/com/example/concordia_campus_guide/Models/PoiType.java
app/src/main/res/raw/rooms_info.json
app/src/main/res/raw/walking_points.json

Updated the walking points and the room points to include lounges and water-fountains.

#176/data collection

---

app/src/androidTest/java/com/example/concordia_campus_guide/InstrumentalTests/LocationFragmentInstrumentalTest.java
app/src/androidTest/java/com/example/concordia_campus_guide/InstrumentalTests/ViewModelFactoryInstrumentalTest.java
app/src/main/java/com/example/concordia_campus_guide/Activities/MainActivity.java
app/src/main/java/com/example/concordia_campus_guide/Activities/PathsActivity.java
app/src/main/java/com/example/concordia_campus_guide/Activities/RoutesActivity.java
app/src/main/java/com/example/concordia_campus_guide/Activities/SearchActivity.java
app/src/main/java/com/example/concordia_campus_guide/Fragments/InfoCardFragment.java
app/src/main/java/com/example/concordia_campus_guide/Fragments/LocationFragment.java
app/src/main/java/com/example/concordia_campus_guide/Fragments/POIFragment.java
app/src/main/java/com/example/concordia_campus_guide/Fragments/PathInfoCardFragment.java
app/src/main/java/com/example/concordia_campus_guide/Fragments/SmallInfoCardFragment.java
app/src/main/java/com/example/concordia_campus_guide/Helper/ViewModelFactory.java
app/src/main/java/com/example/concordia_campus_guide/ViewModels/InfoCardFragmentViewModel.java
app/src/main/java/com/example/concordia_campus_guide/ViewModels/LocationFragmentViewModel.java
app/src/main/java/com/example/concordia_campus_guide/ViewModels/MainActivityViewModel.java
app/src/main/java/com/example/concordia_campus_guide/ViewModels/PathInfoCardViewModel.java
app/src/main/java/com/example/concordia_campus_guide/ViewModels/PathsViewModel.java
app/src/main/java/com/example/concordia_campus_guide/ViewModels/RoutesActivityViewModel.java
app/src/main/java/com/example/concordia_campus_guide/ViewModels/SearchActivityViewModel.java
app/src/main/java/com/example/concordia_campus_guide/ViewModels/SmallInfoCardFragmentViewModel.java
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/paths_activity.xml
app/src/main/res/layout/point_of_interest_fragment.xml
app/src/test/java/com/example/concordia_campus_guide/Activities/PathsViewModelTest.java
app/src/test/java/com/example/concordia_campus_guide/Fragments/PathInfoCardFragmentTest/PathInfoCardViewModelTest.java
app/src/test/java/com/example/concordia_campus_guide/LocationFragmentViewModelTest.java
app/src/test/java/com/example/concordia_campus_guide/ViewModel/InfoCardFragmentViewModelTest.java
app/src/test/java/com/example/concordia_campus_guide/ViewModel/MainActivityViewModelTest.java
app/src/test/java/com/example/concordia_campus_guide/ViewModel/RoutesActivityViewModelTest.java
app/src/test/java/com/example/concordia_campus_guide/ViewModel/SearchActivityViewModelTest.java

This Pull Request was made to separate our view models into their own folders. I personally feel this is cleaner and makes them easier to find.

#265: separated view model into their own package

---

app/src/main/java/com/example/concordia_campus_guide/Helper/PathFinder.java
app/src/test/java/com/example/concordia_campus_guide/HelpersTest/PathFinderTest.java

Initial walking point at the head of a list and destination walking point at the tail of the list.

#268: Return a solution list with the walking points in order

---

app/src/main/java/com/example/concordia_campus_guide/Activities/MainActivity.java
app/src/main/java/com/example/concordia_campus_guide/ClassConstants.java
app/src/main/java/com/example/concordia_campus_guide/Helper/Notification.java
app/src/main/java/com/example/concordia_campus_guide/Models/Helpers/CalendarViewModel.java

The permission for the google calendar will be asked once when the user installs the application for the first time. If the user denies, they can give access to the google calendar through the hamburger menu whenever they want.

#50: google calendar permission fixes

---

app/src/main/java/com/example/concordia_campus_guide/Activities/MainActivity.java

Missing import was causing a compilation error

added missing import

---

app/src/main/java/com/example/concordia_campus_guide/activities/RoutesActivity.java
app/src/main/java/com/example/concordia_campus_guide/helper/IndoorPathHeuristic.java
app/src/main/java/com/example/concordia_campus_guide/helper/PathFinder.java
app/src/main/java/com/example/concordia_campus_guide/models/Building.java
app/src/main/java/com/example/concordia_campus_guide/view_models/PathsViewModel.java
app/src/main/java/com/example/concordia_campus_guide/view_models/RoutesActivityViewModel.java
app/src/main/res/raw/buildings_info.json
app/src/test/java/com/example/concordia_campus_guide/HelpersTest/PathFinderTest.java

- Added an entranceFloor to buildings so that the entrance floor will not be hardcoded every single time.
- Removed some resolved todos (close #180)
fix #227

#227/refactor

---

app/src/main/java/com/example/concordia_campus_guide/activities/SearchActivity.java

Removed duplicated code that SonarQube mentioned.

#258: removed duplicated code

---

app/src/main/java/com/example/concordia_campus_guide/database/daos/WalkingPointDao.java
app/src/main/java/com/example/concordia_campus_guide/helper/PathFinder.java
app/src/test/java/com/example/concordia_campus_guide/HelpersTest/PathFinderTest.java

- Refactored the dao to return a unique walking point when searching by placeCode + floorCode.
- Corresponding unit tests are also refactored.
fix #233

#233/Dao-Refactor: Refactored the walking point getter to return unique point

---

app/src/main/java/com/example/concordia_campus_guide/helper/routes_helpers/DirectionsApiDataParser.java
app/src/main/java/com/example/concordia_campus_guide/models/helpers/RouteBuilder.java
app/src/main/java/com/example/concordia_campus_guide/models/helpers/RouteBuilderDirector.java
app/src/main/java/com/example/concordia_campus_guide/models/routes/Route.java
app/src/main/java/com/example/concordia_campus_guide/view_models/RoutesActivityViewModel.java
app/src/test/java/com/example/concordia_campus_guide/HelpersTest/RoutesHelperTest/DirectionsApiDataParserTest.java
app/src/test/java/com/example/concordia_campus_guide/ModelTests/RouteTest.java
app/src/test/java/com/example/concordia_campus_guide/ViewModel/RoutesActivityViewModelTest.java

Created a RouteBuilder class and a RouteBuilderDirector class to implement the Builder design pattern.

#179: implemented builder pattern

---

app/src/main/java/com/example/concordia_campus_guide/activities/MainActivity.java
app/src/main/java/com/example/concordia_campus_guide/activities/SearchActivity.java
app/src/main/java/com/example/concordia_campus_guide/fragments/LocationFragment.java
app/src/main/java/com/example/concordia_campus_guide/helper/CurrentLocation.java
app/src/main/java/com/example/concordia_campus_guide/helper/CurrentLocationPermissionRequest.java

if the user clicks on my current location from the search page and the user's current location is not available then display a toast.

added a toast when the current location isnot working

---

app/src/main/java/com/example/concordia_campus_guide/helper/CurrentLocation.java
app/src/main/java/com/example/concordia_campus_guide/helper/POIIcon.java
app/src/main/java/com/example/concordia_campus_guide/view_models/LocationFragmentViewModel.java
app/src/main/res/raw/walking_points.json

Washrooms on the 2nd floor of VL did not have corresponding walking points.
Inconsistency between walking point lat/lng and current location lat/lng:
inconsistency was causing errors when looking for distance between current location and a walking point which is needed to sort the POIs

Walking points

---

app/src/androidTest/java/com/example/concordia_campus_guide/activities/ExplorePOIClickTest.java
app/src/androidTest/java/com/example/concordia_campus_guide/activities/InfoCardHallTest.java
app/src/androidTest/java/com/example/concordia_campus_guide/activities/InfoCardVanierLibraryTest.java

Fixed some of the system tests due to the changes happened on the ui.

fixed two system tests

---

app/src/androidTest/java/com/example/concordia_campus_guide/activities/InfoCardVanierLibraryTest.java

fixed the Vanier Library info card system test

Fixing system tests
